### ISSUE TITLE
Custom groups

### ISSUE THREAD

**Issue by BamaRayne** [BamaRayne/Echosistant#91]
Add more device types 

Idea from @JDogg016

**Comment by BamaRayne** [comment]
Not sure if we need more device types in the custom groups, but to actually add them to the main profile choices.

**Comment by BamaRayne** [comment]
Added things to the main groups instead

**Comment by JDogg016** [comment]
Curtains worked great!

Justin Bennett, Esq.

Personal E-Mail Account. Although this was sent from my personal e-mail this communication may contain privileged or other confidential information. If you are not the intended recipient, or believe that you have received this communication in error, please do not print, copy, retransmit, disseminate, or otherwise use the information contained herein. Also, please notify sender that you have received this communication in error, and delete the copy thereof you have received. Thank you.
